### ISSUE TITLE
Author tag on subcommand

### ISSUE THREAD

**Issue by OriginalMHV** [TelenorNorway/tnn#1]
Author tag when using subcommand

**Comment by testersen** [comment]
Apparently this is a [clap.rs configuration](https://github.com/clap-rs/clap/discussions/4316#discussioncomment-5857336), it's just not included in the help template.

I will experiment with this to see if we can fix this in `tnn`, or if this is something extensions will have to implement separately.

**Comment by testersen** [comment]
Tnn needs to rebuild the command-tree with a custom help template to support this.

**Comment by testersen** [comment]
Concluded with that this is something that should be shown in the marketplace, but not when executed by consumers in the terminal.
